replicaCount: 2

app:
  name: ml-app

image:
  repository: dhruvilsatani/ml-app
  tag: 5814fac108e8c2a883a8a8ffc93462edad42a8b6
  pullPolicy: Always

containerPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi

revisionHistoryLimit: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: ""

monitoring:
  enabled: true
  releaseLabel: monitoring
  namespace: monitoring
