apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server
          image: "000000000000.dkr.ecr.us-east-1.localhost:5100/mlflow-server:3.15.2"
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: mlflow-db
                  key: uri
            - name: MLFLOW_ARTIFACTS_DESTINATION
              value: "s3://ml-app-mlflow-artifacts"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://172.18.0.2:4566"