{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}-monitor
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: {{ .Values.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}